steps:
  # Instala dependências do projeto
  - name: 'node:22'
    entrypoint: 'npm'
    args: ['install']

  # Build do Angular (ajuste o caminho se necessário)
  - name: 'node:22'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/chat-bot-ng', '.']

  # Deploy no Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'chat-bot-ng',
        '--image', 'gcr.io/$PROJECT_ID/chat-bot-ng',
        '--region', 'southamerica-east1', # ajuste a região se necessário
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]

images:
  - 'gcr.io/$PROJECT_ID/chat-bot-ng'